# Docs: https://docker-minecraft-server.readthedocs.io/en/latest/
services:
  mc:
    container_name: example
    image: itzg/minecraft-server:java21 # Minecraft 1.20.5 and newer
    #image: itzg/minecraft-server:java17 # Minecraft 1.17 until 1.20.4
    #image: itzg/minecraft-server:java8  # Minecraft 1.16 and older
    tty: true
    stdin_open: true
    restart: unless-stopped
    # swap networks, ports & labels comments when using mc-router
    #networks:
    #  - minecraft
    #  - default
    ports:
      - "25565:25565" # Minecraft
      - "24454:24454/udp" # simple-voice-chat
    #labels:
    #  mc-router.host: "mc.example.org"
    environment:
      UID: 1001
      GID: 1001
      # Setups
      EULA: "TRUE"
      #MEMORY: 8G # initial and maximum Java memory-heap, 8G is max recommended, above this benefits stop
      #TYPE: VANILLA
      #VERSION: LATEST # The minecraft version
      #WORLD: /worlds/basic # For loading external world saves
      
      # server.properties
      MOTD: |
        line one
        line two
      #DIFFICULTY: hard # peaceful, easy, normal, and hard
      ICON: /icon.png
      #MAX_WORLD_SIZE: 10000 # world border raidus
      BROADCAST_RCON_TO_OPS: false
      #OVERRIDE_SERVER_PROPERTIES: false # Uncomment to manually manage server.properties
      #SKIP_SERVER_PROPERTIES: true # Uncomment to skip all scripted creation

      #STOP_SERVER_ANNOUNCE_DELAY: 60 # In seconds, match to grace
    #stop_grace_period: 120s
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ${PWD}/../mc-files/whitelist.json:/data/whitelist.json
      - ${PWD}/../mc-files/ops.json:/data/ops.json
      - ${PWD}/icon.png:/icon.png:ro

  backup:
    image: itzg/mc-backup
    user: "1001:1001"
    depends_on:
      mc:
        condition: service_healthy
    environment:
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      RCON_HOST: mc
      BACKUP_INTERVAL: 1h
      PRE_SAVE_ALL_SCRIPT: /pre-backup.sh
      POST_BACKUP_SCRIPT: /post-backup.sh
      BACKUP_METHOD: restic
      RESTIC_PASSWORD: password # Change this
      RESTIC_REPOSITORY: /backups
      PRUNE_RESTIC_RETENTION: --keep-last 16 --keep-hourly 24 --keep-daily 3 --keep-weekly 7 --keep-monthly 12 
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
      - ${PWD}/../mc-files/pre-backup.sh:/pre-backup.sh:ro
      - ${PWD}/../mc-files/post-backup.sh:/post-backup.sh:ro

networks:
  minecraft:
    external: true